# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GA_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageview', models.IntegerField()),
                ('bouncerate', models.FloatField()),
                ('transactions', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('sessions', models.IntegerField()),
                ('costPerTransaction', models.FloatField()),
                ('impressions', models.IntegerField()),
                ('adClicks', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('profile', models.CharField(max_length=100)),
            ],
        ),
    ]
