# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ga_data',
            name='profile',
            field=models.CharField(default='Bonia', max_length=100),
            preserve_default=False,
        ),
    ]
