# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ga_data_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ga_data',
            name='adClicks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ga_data',
            name='costPerTransaction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ga_data',
            name='ctr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ga_data',
            name='impressions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ga_data',
            name='sessions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
